services:
  db:
    image: mariadb:latest
    container_name: remote_db_server
    restart: always
    environment:
      MARIADB_USER: LOCAL_ADMIN
      MARIADB_PASSWORD: "abc123."
      MARIADB_DATABASE: theroundtable
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "9001:3306"
    networks:
      - trt-net
  
  rest_api:
    image: ubuntu:latest
    container_name: trt_server
    restart: always
    environment:
      TRT_DB_CONN: mariadb://LOCAL_ADMIN:abc123.@remote_db_server:3306/theroundtable
    volumes:
      - ./output/trt-server-side:/srv/trt_server
    command:
      - "/srv/trt_server/app/server_side"
    networks:
      - trt-net
  
  plugin_repository:
    image: ubuntu:latest
    container_name: trt_plugin_repository
    restart: always
    networks:
      - trt-net
  
networks:
  trt-net:
    driver: bridge
