services:
  db:
    image: mariadb:latest
    container_name: remote_db_server
    restart: always
    environment:
      MARIADB_USER: LOCAL_ADMIN
      MARIADB_PASSWORD: "abc123."
      MARIADB_DATABASE: theroundtable
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "9500:3306"
    networks:
      - trt-net
  
  rest_api:
    image: ubuntu:latest
    container_name: trt_rest_api
    restart: always
    environment:
      TRT_DB_CONN: mariadb://LOCAL_ADMIN:abc123.@remote_db_server:3306/theroundtable
    volumes:
      - ./output/trt-central/bin/rest-api:/srv/trt_central/bin/rest-api:ro
      - ./output/trt-central/resources:/srv/trt_central/resources:ro
    command:
      - "/srv/trt_central/bin/rest-api"
    ports:
      - "9501:8000"
    networks:
      - trt-net
  
  plugin_repo:
    image: ubuntu:latest
    container_name: trt_plugin_repo
    restart: always
    environment:
      TRT_PLUGINS_REPO_DIR: /srv/trt_plugin_repo/plugins
      TRT_PLUGINS_REPO_PORT: 1238
      TRT_PLUGINS_REPO_PASSWORD: abc123.
      TRT_PLUGINS_REPO_ADDRS: 0.0.0.0
    volumes:
      - ./output/trt-central/bin/plugin-repo:/srv/trt_plugin_repo/bin/plugin-repo:ro
      - ./output/trt-central/plugins:/srv/trt_plugin_repo/plugins
    command:
      - "/srv/trt_plugin_repo/bin/plugin-repo"
    ports:
      - "9502:1238"
    networks:
      - trt-net
  
  dev_plugin_repo:
    image: ubuntu:latest
    container_name: trt_dev_plugin_repo
    restart: always
    environment:
      TRT_PLUGINS_REPO_DIR: /srv/trt_plugin_repo/plugins
      TRT_PLUGINS_REPO_PORT: 1238
      TRT_PLUGINS_REPO_PASSWORD: abc123.
      TRT_PLUGINS_REPO_ADDRS: 0.0.0.0
    volumes:
      - ./output/trt-central/bin/plugin-repo:/srv/trt_plugin_repo/bin/plugin-repo:ro
      - ./output/trt-central/dev-plugins:/srv/trt_plugin_repo/plugins
    command:
      - "/srv/trt_plugin_repo/bin/plugin-repo"
    ports:
      - "9503:1238"
    networks:
      - trt-net
  
networks:
  trt-net:
    external: true
    name: trt-net
