<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.lebastudios.theroundtableplugins</groupId>
    <artifactId>plugins</artifactId>
    <version>3.0.0</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>org.lebastudios.theroundtable</groupId>
        <artifactId>global-config</artifactId>
        <version>3.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    
    <modules>
        <module>accounting</module>
        <module>cr</module>
        <module>floor-plan</module>
        <module>rm</module>
        <module>sb</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.2.0</version>
                    <configuration>
                        <outputDirectory>${project.basedir}</outputDirectory>
                        <finalName>${project.artifactId}</finalName>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
